### ISSUE TITLE
Could you write a script to open the JWEMS Files ?

### ISSUE THREAD

**Issue by Mcflyhigh1** [Pathos0925/JWEM#11]
Just a Question, i try to use a JWEMS Texture as Texture for a 3D Model... could you write a script what convert this format into a picture format ?

**Comment by Pathos0925** [comment]
The .jwems format was not designed for that. You'll need to use .png or some other format. If you were thinking of Direct X's texture format, .dds, there is a plugin for Photoshop that you can use to open and save those files: https://developer.nvidia.com/nvidia-texture-tools-adobe-photoshop

**Comment by Mcflyhigh1** [comment]
I know Pathos... i just try to reimport a JWEMS file into a paint program "to change the paintjob, what i did few weeks ago"..
