### ISSUE TITLE
I'm doing something wrong

### ISSUE THREAD

**Issue by MichaelFitz23** [Pathos0925/JWEM#2]
When I open the menu in-game I hit the dinosaurs drop-down box and no dinosaurs show up. If someone could please help me get this menu working I would be ever so thankful.

**Comment by MichaelFitz23** [comment]
Or possibly make a how to install video.

**Comment by Pathos0925** [comment]
Have you released a dinosaur in your save, it only finds dinosaurs that have been released and with basic skins. Also make sure you have the two text files, FULLCRC_LIST.txt and SKIN_IDS.txt in your JWE directory as well.

**Comment by MichaelFitz23** [comment]
Yes, I've tried re-releasing dinos and even doing new save files. I have both the text files but it still doesn't seem to work. Here are some pictures of my directory and my game.
![game](https://user-images.githubusercontent.com/44762937/48015327-230db180-e0e6-11e8-85cf-9b62f8e4db07.png)
![directory](https://user-images.githubusercontent.com/44762937/48015338-2acd5600-e0e6-11e8-950e-ff9737db6199.png)

**Comment by MichaelFitz23** [comment]
@Pathos0925 > Have you released a dinosaur in your save, it only finds dinosaurs that have been released and with basic skins. Also make sure you have the two text files, FULLCRC_LIST.txt and SKIN_IDS.txt in your JWE directory as well.

Yes, I've tried re-releasing dinos and even doing new save files. I have both the text files but it still doesn't seem to work. Here are some pictures of my directory and my game.
![game](https://user-images.githubusercontent.com/44762937/48019212-1a21dd80-e0f0-11e8-880f-26a5abd530a3.png)
![directory](https://user-images.githubusercontent.com/44762937/48019220-1c843780-e0f0-11e8-974c-a3d1100870cb.png)
@Pathos0925

**Comment by henryscp** [comment]
i habe relesed a dinosuar but the skins dont show up

**Comment by MichaelFitz23** [comment]
> i habe relesed a dinosuar but the skins dont show up

so its not just my game then

**Comment by Pathos0925** [comment]
If you could send me your log file (either dxgi.log or d3d11.log) either via email or through a discord private message, I can look into this further.

**Comment by MichaelFitz23** [comment]
> If you could send me your log file (either dxgi.log or d3d11.log) either via email or through a discord private message, I can look into this further.

Okay but you dont have to make it top priority, what you are doing is amazing. Can you private message  me your email somehow

**Comment by Pathos0925** [comment]
In the games graphics settings, make sure your texture quality is set to medium or high.

**Comment by henryscp** [comment]
my texture quality is on high whats the discord link?

**Comment by Pathos0925** [comment]
Additional compatibility for more systems will be looked into in further releases.
